apiVersion: v1
kind: Service
metadata:
  name: user-app-service
spec:
  type: LoadBalancer  # Exposes the Service externally using a cloud provider's load balancer
  ports:
    - port: 83
      targetPort: 5000  # Port on the container
      protocol: TCP
  selector:
    app: user-app
