apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-app-deployment
spec:
  replicas: 1  # Number of replicas
  selector:
    matchLabels:
      app: user-app
  template:
    metadata:
      labels:
        app: user-app
    spec:
      containers:
      - name: user-app
        image: europe-west3-docker.pkg.dev/int-infra-training-gcp/maamoun/userapp:latest  # Replace with your actual Docker image path
        imagePullPolicy: Always
        ports:
        - containerPort: 5000  # The port your app runs on
        volumeMounts:
          - name: pv-storage
            mountPath: /mnt/gcs  
        env:
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: my-secrets
                key: SECRET_KEY
          - name: GITHUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: my-secrets
                key: GITHUB_TOKEN
      volumes:
      - name: pv-storage
        persistentVolumeClaim:
          claimName: bert-fine-tuning-pipeline-mvlnn-mypvc
      # Optional: Add other environment setup here, like database connections
